#!/bin/bash

function usage() {
    echo "Usage: ${0} [type [options]] <file>"
    echo "  depgra  - Generate a dependency graph"
    echo "  flexgra - Generate a scanner graph"
}

if [[ $# -eq 0 ]]; then
    usage
    exit 1
fi

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    usage
    exit 0
fi

TYPE="depgra" # default value

if [[ $# -eq 1 ]]; then
    FILE="$1"
else
    TYPE="$1"
    OPTIONS="${@:2:$(($#-2))}"
    FILE="${@: -1}"
fi

case "$TYPE" in
    depgra)
        depgra $OPTIONS "$FILE"
        dot -Tpng -o dependency_graph.png c.dot
        ;;
    flexgra)
        flexgra $OPTIONS "$FILE"
        dot -Tpng -o scanner_graph.png out.dot
        ;;
    *)
        usage
        exit 1
        ;;
esac
